plugins {
    id 'groovy-gradle-plugin'
}

repositories {
    gradlePluginPortal()
}

dependencies {
    // Upload plugins used by the multiloader-publish convention plugin
    implementation 'com.modrinth.minotaur:com.modrinth.minotaur.gradle.plugin:2.+'
    implementation 'net.darkhax.curseforgegradle:net.darkhax.curseforgegradle.gradle.plugin:1.1.+'
}
